# Generated by Django 4.2.7 on 2023-11-04 12:35

from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.contrib.routable_page.models
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0089_log_entry_data_json_null_to_object'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('subHeader', wagtail.fields.StreamField([('header', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock()), ('subtitle', wagtail.blocks.CharBlock())], label='Заголовок'))], default='', use_json_field=True)),
                ('title_buttons', wagtail.fields.StreamField([('title_button', wagtail.blocks.StructBlock([('icon', wagtail.blocks.CharBlock()), ('title', wagtail.blocks.CharBlock())], label='Кнопка под верхним блоком'))], default='', use_json_field=True)),
                ('functional_description', wagtail.fields.StreamField([('left_block', wagtail.blocks.StructBlock([('header', wagtail.blocks.CharBlock()), ('description', wagtail.blocks.CharBlock())], label='Правый блок')), ('right_block', wagtail.blocks.StructBlock([('header', wagtail.blocks.CharBlock()), ('description', wagtail.blocks.CharBlock())], label='Левый блок')), ('image', wagtail.images.blocks.ImageChooserBlock())], default='', use_json_field=True)),
                ('card_carousel', wagtail.fields.StreamField([('header', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock()), ('subtitle', wagtail.blocks.CharBlock())], label='Заголовок')), ('card', wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('title', wagtail.blocks.CharBlock()), ('description', wagtail.blocks.CharBlock()), ('hint', wagtail.blocks.CharBlock())], label='Карточка'))], default='', use_json_field=True)),
                ('contacts', wagtail.fields.StreamField([('column', wagtail.blocks.RichTextBlock(label='Столбец'))], default='', use_json_field=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(wagtail.contrib.routable_page.models.RoutablePageMixin, 'wagtailcore.page'),
        ),
    ]
