# Generated by Django 4.2.5 on 2023-10-04 11:49

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_homepage_body_homepage_subtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='rtrbody',
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
    ]
