# Generated by Django 4.2.5 on 2023-10-04 14:08

from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.embeds.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0089_log_entry_data_json_null_to_object'),
        ('home', '0007_homepage_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='RatesPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('figcaptionblock', wagtail.blocks.StructBlock([('figure', wagtail.images.blocks.ImageChooserBlock()), ('caption', wagtail.blocks.CharBlock())])), ('rtfblock', wagtail.blocks.RichTextBlock(features={'bold', 'h1', 'link', 'code'}, help_text='Описание', label='Текст')), ('image', wagtail.images.blocks.ImageChooserBlock(help_text='Изображение', label='Фото', template='blocks/imgblock.html')), ('youtubeblock', wagtail.embeds.blocks.EmbedBlock(help_text='Ютуб', icon='success', label='Видео'))], blank=True, use_json_field=True),
        ),
    ]
