# Generated by Django 4.2.5 on 2023-10-04 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0089_log_entry_data_json_null_to_object'),
        ('home', '0008_ratespage_alter_homepage_body'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RatesPage',
            new_name='Tariffs',
        ),
    ]
