# Generated by Django 4.2.5 on 2023-10-04 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_rename_ratespage_tariffs'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tariffs',
        ),
    ]
